### ISSUE TITLE
Добавиь новые строки

### ISSUE THREAD

**Issue by AndreyShovkun** [Shavius/Test_Project#1]
Добавиь новые строки хотябы еще 3 штуки @Shavius 
Например:
- Строка 1
- Строка 2
- Строка 3
### Ну пока все

**Comment by Shavius** [comment]
Хороше @AndreyShovkun Я добавлю эти строки 👍

**Comment by Shavius** [comment]
Также возможно я внесу это все в новую версию 👍 
та будут строки:

- [ ] Строка 1
- [ ] Строка 2
- [ ] Строка 3

**Comment by AndreyShovkun** [comment]
Хороше 👍

**Comment by AndreyShovkun** [comment]
Может добавишь еще 2 команды чтобы их было 5 штук всего ?

**Comment by Shavius** [comment]
Хороше

**Comment by Shavius** [comment]
Ну как годиться ?

**Comment by AndreyShovkun** [comment]
Да
